integralfamilies:

  - name: "T1"
    loop_momenta: [k1, k2]
    propagators:
      - [ "k1", 0 ]
      - [ "k1+p1", 0 ]
      - [ "k1-p2", 0 ]
      - [ "k2", 0 ]
      - [ "k2+p1", 0 ]
      - [ "k2-p2", 0 ]
      - [ "k1-k2", 0 ]
      - [ "k1+p3", 0 ]
      - [ "k2+p3", 0 ]


  - name: "T2"
    loop_momenta: [k1, k2]
    propagators:
      - [ "k1", 0 ]
      - [ "k1+p1", 0 ]
      - [ "k2-p2", 0 ]
      - [ "k2", 0 ]
      - [ "k1+k2+p1", 0 ]
      - [ "k1+k2-p2", 0 ]
      - [ "k1+k2", 0 ]
      - [ "k1+p3", 0 ]
      - [ "k2+p3", 0 ]



