jobs:
  - reduce_sectors:
      conditional: false
      sector_selection:
         select_recursively:
           - [T1, 86]
           - [T1, 118]
           - [T1, 54]
           - [T1, 79]
           - [T1, 95]
           - [T1, 111]
           - [T1, 87]
           - [T1, 103]
           - [T1, 119]
           - [T1, 55]
           - [T2, 63]

      identities: # in general, DEQs might require larger (r,s)-range than this
        ibp:
          - { r: [t, 8], s: [0, 3] }
        lorentz: # may help to reduce certain integrals at border of seed range
          - { r: [t, t], s: [0, 3] }
        sector_symmetries: # sometimes important, doesn't harm
          - { r: [t, t], s: [0, 3] }
      solutions:
        requested_solutions:
          - { r: [t, 9], s: [0, 3] }
      reduzer_options:
        num_equations_per_subjob: 1
      num_seeds_for_identities_auxjobs: 1000
      delete_temporary_files: true

