jobs:
# compute the derivatives
  - compute_differential_equations:
      conditional: false
      integrals_file: "masters.curr.m"
      output_file: "tmp/deq.unred"
      set_subsectors_to_zero: false

# get reductions for differential equations
  - collect_integrals:
      input_file: "tmp/deq.unred"
      output_file: "tmp/ints.deq"
  - select_reductions:
      input_file: "tmp/ints.deq"
      output_file: "tmp/red.deq"
      preferred_masters_file: "masters.curr.m"

# get identities for basis change
  - select_reductions:
      input_file: "masters.curr.m"
      output_file: "tmp/sel.masters.curr"
#      preferred_masters_file: "masters.curr.m"

# perform basis change
  - reduce_files:
      equation_files:
        - "tmp/red.deq"
        - "tmp/sel.masters.curr"
      output_file: "tmp/red.deq.newbasis"
      preferred_masters_file: "masters.curr.m"

# insert reductions in derivatives
  - insert_reductions:
      input_file: "tmp/deq.unred"
      reductions_file: "tmp/red.deq.newbasis"
      preferred_masters_file: "masters.curr.m"
      output_file: "tmp/deq.red"
  - normalize:
      input_file: "tmp/deq.red"
      output_file: "tmp/deq2.red"
      preferred_masters_file: "masters.curr.m"

# insert extra identities PP:5:62
#  - insert_reductions:
#      input_file: "tmp/deq6.red"
#      reductions_file: "../Reductions_PLANAR/reductions/reduction_PPgg_5_62"
#      preferred_masters_file: "masters.curr.m"
#      output_file: "tmp/deq7.red"
#  - normalize:
#      input_file: "tmp/deq7.red"
#      output_file: "tmp/deq8.red"
#      preferred_masters_file: "masters.curr.m"

# expand in eps and export to Mathematica format
  - export:
      input_file: "tmp/deq2.red"
      output_file: "deq.m"
      output_format: "mma"
      preferred_masters_file: "masters.curr.m"

