kinematics :
  incoming_momenta: [ p1, p2 ]
  outgoing_momenta: [ pw, ph, p5 ]
  momentum_conservation: [ ph, "p1 + p2 - pw - p5" ]
  kinematic_invariants:
    - [s, 2]
    - [t, 2]
    - [u, 2]
    - [s14, 2]
    - [s15, 2]
    - [s24, 2]
    - [s25, 2]
    - [s35, 2]
    - [mw, 1]
    - [mh, 1]
  scalarproduct_rules:
    - [[p1,p1],  "0"]
    - [[p2,p2],  "0"]
    - [[p5,p5],  "0"]
    - [[pw,pw],  "mw^2"]
    - [[p1,p2],  "s/2"]
    - [[p1,pw],  "(mw^2-t)/2"]
    - [[p1,p5],  "s15/2"]
    - [[p2,pw],  "(mw^2-u)/2"]
    - [[p2,p5],  "s25/2"]
    - [[p5,pw],  "(s35-mw^2)/2"]
  symbol_to_replace_by_one: s

