jobs:
    - select_reductions:
        conditional: false
        input_file: "/net/home/lxtsfs1/tpe/korneev/Desktop/NNLO_Single_Real/REDUZE/List_of_integrals.yaml"
        output_file: "masters_tmp/tmp/AMP_MI.sol"
        notfound_file: "masters_tmp/MI_NF.rest"
        generate_crossed: false
#gnerate_crossed is set to false because this is already the full list of integrals that is needed.
#### First ensure complete reduction with reduze basis
    - reduce_files:
        conditional: false
        equation_files:
          - "masters_tmp/tmp/AMP_MI.sol"
        output_file: "masters_tmp/tmp/AMP_MIF2.sol"
        reduzer_options:
          num_equations_per_subjob: 1
    - reduce_files:
        conditional: false
        equation_files:
          - "masters_tmp/tmp/AMP_MIF2.sol"
#        preferred_masters_file: "masters.curr.m"
        output_file: "masters_tmp/tmp/AMP_MIF3.sol"
        reduzer_options:
          num_equations_per_subjob: 1
    - export:
        input_file: "masters_tmp/tmp/AMP_MIF3.sol"
        output_file: "masters_tmp/sector_sub.inc"
        output_format: "form"
