integralfamilies:

  - name: "INT"
    loop_momenta: [k]
    propagators:
      - [ "k", 0 ]
      - [ "p1+k", 0 ]
      - [ "p1+p2+k", 0 ]
      - [ "p1+p2-p5+k", 0 ]
      - [ "p1+p2-p5-pw+k", 0 ]






