kinematics :
  incoming_momenta: [ p1, p2, p3, p4, p5 ]
  outgoing_momenta: [  ]
  momentum_conservation: [ p4, "-p1 - p2 - p3 - p5" ]
  kinematic_invariants:
    - [s12, 2]
    - [s13, 2]
#    - [s14, 2]
    - [s15, 2]
    - [s23, 2]
#    - [s24, 2]
    - [s25, 2]
    - [s35, 2]
    - [mv, 1]
    - [mh, 1]
  scalarproduct_rules:
    - [[p1,p1], 0 ]
    - [[p2,p2], 0 ]
    - [[p5,p5], 0 ]
    - [[p3,p3], "mv^2" ]
    - [[p1,p2], "s12/2" ]
    - [[p1,p3], "(s13-mv^2)/2" ]
#    - [[p1,p4], "(s14-mh^2)/2" ]
    - [[p1,p5], "s15/2" ]
    - [[p2,p3], "(s23-mv^2)/2" ]
#    - [[p2,p4], "(s24-mh^2)/2" ]
    - [[p2,p5], "s25/2" ]
    - [[p3,p5], "(s35-mv^2)/2" ]
#  symbol_to_replace_by_one: s12

