integralfamilies:
  - name: "RLO"
    top_level_sectors: [15]
    magic_relations: true
    loop_momenta: [k1]
    propagators:
      - [ "k1", 0 ]
      - [ "k1+p1", 0 ]
      - [ "k1+p1+p2", 0 ]
      - [ "k1+p1+p2+p5", 0 ]
      - [ "k1+p1+p2+p5+p3", 0 ]

  - name: "RLOx12"
    top_level_sectors: [15]
    magic_relations: true
    loop_momenta: [k1]
    propagators:
      - [ "k1", 0 ]
      - [ "k1+p2", 0 ]
      - [ "k1+p1+p2", 0 ]
      - [ "k1+p1+p2+p5", 0 ]
      - [ "k1+p1+p2+p5+p3", 0 ]

  - name: "RLOx125"
    top_level_sectors: [15]
    magic_relations: true
    loop_momenta: [k1]
    propagators:
      - [ "k1", 0 ]
      - [ "k1+p2", 0 ]
      - [ "k1+p2+p5", 0 ]
      - [ "k1+p1+p2+p5", 0 ]
      - [ "k1+p1+p2+p5+p3", 0 ]

