kinematics :
  incoming_momenta: [ p1, p2 ]
  outgoing_momenta: [ p3, p4 ]
  momentum_conservation: [ p4, "p1 + p2 - p3" ]
  kinematic_invariants:
    - [s, 2]
    - [t, 2]
    - [mw, 1]
    - [mh, 1]
  scalarproduct_rules:
    - [[p1,p1],  "0"]
    - [[p2,p2],  "0"]
    - [[p3,p3],  "mw^2"]
    - [[p4,p4],  "mh^2"]
    - [[p1,p2],  "s/2"]
    - [[p1,p3],  "(mw^2-t)/2"]
    - [[p2,p3],  "(s+t-mh^2)/2"]
  symbol_to_replace_by_one: mw

